/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Irvina
 */
public class Tugas1 extends javax.swing.JFrame {

    /**
     * Creates new form Tugas1
     */
    public Tugas1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etAbsen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        etKelas = new javax.swing.JTextField();
        etAlamat = new javax.swing.JTextField();
        etNilai = new javax.swing.JTextField();
        etNama = new javax.swing.JTextField();
        buttonPro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        etAbsen.setBackground(new java.awt.Color(153, 255, 204));
        etAbsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etAbsenActionPerformed(evt);
            }
        });
        getContentPane().add(etAbsen);
        etAbsen.setBounds(180, 110, 170, 30);

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("NILAI");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 270, 90, 20);

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("NAMA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 70, 90, 20);

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("ABSEN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 120, 90, 20);

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("KELAS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 170, 90, 20);

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("ALAMAT");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 220, 100, 20);

        etKelas.setBackground(new java.awt.Color(153, 255, 204));
        etKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etKelasActionPerformed(evt);
            }
        });
        getContentPane().add(etKelas);
        etKelas.setBounds(180, 160, 170, 30);

        etAlamat.setBackground(new java.awt.Color(153, 255, 204));
        etAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(etAlamat);
        etAlamat.setBounds(180, 210, 170, 30);

        etNilai.setBackground(new java.awt.Color(153, 255, 204));
        etNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etNilaiActionPerformed(evt);
            }
        });
        getContentPane().add(etNilai);
        etNilai.setBounds(180, 260, 170, 30);

        etNama.setBackground(new java.awt.Color(153, 255, 204));
        etNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etNamaActionPerformed(evt);
            }
        });
        getContentPane().add(etNama);
        etNama.setBounds(180, 60, 170, 30);

        buttonPro.setBackground(new java.awt.Color(153, 255, 204));
        buttonPro.setText("PROSES");
        buttonPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPro);
        buttonPro.setBounds(180, 320, 110, 23);

        Hasil.setBackground(new java.awt.Color(204, 255, 255));
        Hasil.setColumns(20);
        Hasil.setRows(5);
        jScrollPane1.setViewportView(Hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 370, 320, 140);

        jLabel7.setText(":");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 270, 10, 20);

        jLabel8.setText(":");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 120, 10, 20);

        jLabel9.setText(":");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 70, 10, 20);

        jLabel10.setText(":");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 170, 10, 20);

        jLabel11.setText(":");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(160, 220, 10, 20);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("FORM PENILAIAN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(165, 21, 170, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 480, 530);

        setBounds(0, 0, 498, 568);
    }// </editor-fold>//GEN-END:initComponents

    private void etAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etAbsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etAbsenActionPerformed

    private void etKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etKelasActionPerformed

    private void etAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etAlamatActionPerformed

    private void etNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etNilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etNilaiActionPerformed

    private void etNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etNamaActionPerformed

    private void buttonProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProActionPerformed
    String nama = etNama.getText();
    String absen = etAbsen.getText();
    String kelas = etKelas.getText();
    String alamat = etAlamat.getText();
    int nilai = Integer.parseInt(etNilai.getText());
    
    Hasil.setText("\n NAMA : " +nama+ "\n ABSEN : " +absen+ 
            "\n KELAS : " +kelas+ "\n ALAMAT : " +alamat+ 
            "\n NILAI : " +nilai+ "\n");

    if (nilai >= 86 && nilai <=100)
    {
        Hasil.append(" Selamat NILAI Anda Sempurna \n");
    }
    else if (nilai >=75 && nilai <=85)
    {
        Hasil.append(" Anda LULUS \n");
    }
    else if(nilai <=74)
    {
        Hasil.append(" Anda TIDAK LULUS \n");
    }
    else
    {
        Hasil.append(" Pastikan Nilai Anda Benar \n");
    }// TODO add your handling code here:
    }//GEN-LAST:event_buttonProActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Hasil;
    private javax.swing.JButton buttonPro;
    private javax.swing.JTextField etAbsen;
    private javax.swing.JTextField etAlamat;
    private javax.swing.JTextField etKelas;
    private javax.swing.JTextField etNama;
    private javax.swing.JTextField etNilai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
